### ISSUE TITLE
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by PonyWarrior** [derekantrican/APCAlert#1]
Hello, I have followed your instructions and am getting this error when running APCAlert.exe :

`Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Program.<Main>$(String[] args) in C:\Users\Wakanda\Documents\APCAlert-master\Program.cs:line 12
   at Program.<Main>(String[] args)`

This happens even when I don't change anything in Program.cs. I don't see a log anywhere unfortunately, let me know if there's one I don't know about.

**Comment by derekantrican** [comment]
How are you running APCAlert.exe? APCAlert.exe is designed to be called from the batch script files. If you're trying to test it, you can run (from command prompt) `APCAlert.exe onbattery`

**Comment by derekantrican** [comment]
I made a tweak to the code (https://github.com/derekantrican/APCAlert/commit/a34dd513fbd166209dc29c0f783e4a0998dc305b) - test it out and let me know how it works for you

**Comment by PonyWarrior** [comment]
Ok, I just figured out it was called by apcups and not ran manually as I thought. Not sure if your commit fixed anything, but thanks for the help it works great.

**Comment by derekantrican** [comment]
Yes, it is called through apcupsd, but through the batch files. apcupsd looks for batch files matching certain events (like `onbattery.bat` or `offbattery.bat`) in the `C:\apcupsd\etc\apcupsd` directory. This program installs them when you run `dotnet build` (they are defined here: https://github.com/derekantrican/APCAlert/blob/master/APCAlert.csproj#L10C1-L19C25)
